# Generated by Django 5.0.2 on 2024-02-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('serial', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('repassword', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('chackbox', models.CharField(max_length=50)),
                ('payment', models.IntegerField()),
                ('django', models.CharField(max_length=50)),
            ],
        ),
    ]
